# Generated by Django 5.2.6 on 2025-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(blank=True, upload_to='comments/images/%Y/%m/', verbose_name='Image')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Edited')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
