# Generated by Django 5.2.6 on 2025-09-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Subject name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Subject code')),
                ('semester', models.PositiveIntegerField(verbose_name='Semester')),
                ('credits', models.PositiveIntegerField(verbose_name='Credits')),
                ('subject_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('elective', 'Elective'), ('optional', 'Optional')], default='mandatory', max_length=15, verbose_name='Subject type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='career.career', verbose_name='Career')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='subject.subject', verbose_name='Prerequisites')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['career', 'semester', 'name'],
                'unique_together': {('career', 'code')},
            },
        ),
    ]
