# Generated by Django 5.2.6 on 2025-09-30 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('note_type', models.CharField(choices=[('class', 'Class Notes'), ('summary', 'Summary'), ('exercise', 'Exercise'), ('project', 'Project'), ('exam', 'Exam Material'), ('reference', 'Reference')], default='class', max_length=15, verbose_name='Note type')),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=10, verbose_name='Privacy level')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('file_attachment', models.FileField(blank=True, upload_to='notes/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'png'])], verbose_name='File attachment')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views count')),
                ('downloads_count', models.PositiveIntegerField(default=0, verbose_name='Downloads count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Note Favorite',
                'verbose_name_plural': 'Note Favorites',
                'ordering': ['-created_at'],
            },
        ),
    ]
